{
 "title": "Jetstream",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(jetstream_events_emitted_total,job)"
    }
   },
   {
    "name": "exporter_job",
    "label": "Exporter Job",
    "query": {
     "query": "label_values(node_network_receive_bytes_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Operation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(consumer_ops_processed_total{job=~\"${job}\"}[$__rate_interval]) > 0",
     "legendFormat": "{{kind}} {{op_path}}"
    }
   ]
  },
  {
   "title": "Subscriber Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(jetstream_events_delivered_total{job=~\"${job}\"}[$__rate_interval])> 0",
     "legendFormat": "{{ip_address}}"
    },
    {
     "expr": "rate(jetstream_bytes_delivered_total{job=~\"${job}\"}[$__rate_interval]) * 8 > 0",
     "legendFormat": "{{ip_address}}"
    }
   ]
  },
  {
   "title": "Consumer Firehose Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(indigo_repo_stream_bytes_total{job=~\"${job}\"}[$__rate_interval]) * 8 > 0",
     "legendFormat": "Bytes In"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"${job}\"}[$__rate_interval])",
     "legendFormat": "CPU Seconds per Second"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"${job}\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Consumer Event Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(consumer_event_processing_duration_seconds_bucket{job=~\"${job}\"}[$__rate_interval])) by (le)) > 0",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(consumer_event_processing_duration_seconds_bucket{job=~\"${job}\"}[$__rate_interval])) by (le)) > 0",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(consumer_event_processing_duration_seconds_bucket{job=~\"${job}\"}[$__rate_interval])) by (le)) > 0",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$exporter_job\",device!~'rootfs', mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"$exporter_job\", device!~'rootfs', mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$exporter_job\", device=\"ens3\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$exporter_job\", device=\"ens3\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  }
 ]
}